# Data Analytics  Notebook 1
## By: Jesse, Sumana, Adriel

In [8]:
import numpy as np
import pandas as pd
import sqlite3

### Super Store Data

In [9]:
conn = sqlite3.connect('superstore.db') 
          
sql_query = pd.read_sql_query ('''
                               SELECT
                               *
                               FROM superstore
                               ''', conn)

df = pd.DataFrame(sql_query)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
1,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
4,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9989,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9990,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9991,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9992,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [10]:
sales = df["Sales"]
city = df["City"]
row_id = df["Row_ID"]
order_id = df["Order_ID"]
ship_mode = df["Ship_Mode"]
cust_id = df["Customer_ID"]
segment = df["Segment"]
country = df["Country"]
city = df["City"]
state = df["State"]
postal_cd = df["Postal_Code"]
region = df["Region"]
prod_id = df["Product_ID"]
cat = df["Category"]
sub_cat = df["Sub_Category"]
quant = df["Quantity"]
discount = df["Discount"]
profit = df["Profit"]

In [11]:
df.head(5)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
1,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
4,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694

# Data Groups

- Products Sold
- Unique Cities
- Unique Customers
- Unique Products
- Unique Categories
- Ship Mode counts
- Unique Order Dates / Count
- Unique Ship Dates / Count

In [12]:
reg_count = df['Region'].value_counts()
reg_count

West       3203
East       2848
Central    2323
South      1619
Name: Region, dtype: int64

In [13]:
prod_sold_per_region = df.groupby('Region')['Product_ID'].nunique()
prod_sold_per_region

Region
Central    1310
East       1422
South      1057
West       1509
Name: Product_ID, dtype: int64

In [17]:
unique_cities = df['City'].value_counts().count()
unique_states = df['State'].value_counts().count()
unique_customers = df['Customer_ID'].value_counts().count()
unique_products = df['Product_ID'].value_counts().count()

unique_cities

531

In [18]:
ship_mode_count = df['Ship_Mode'].value_counts()
ship_date_count = df['Ship_Date'].value_counts()
order_date_count = df['Order_Date'].value_counts()
cat_count = df['Category'].value_counts()
reg_count = df['Region'].value_counts()
sub_cat_count = df['Sub_Category'].value_counts()

ship_mode_count

Standard Class    5968
Second Class      1944
First Class       1538
Same Day           543
Name: Ship_Mode, dtype: int64

In [19]:
prod_sold_per_city = df.groupby('City')['Product_ID'].nunique()
prod_sold_per_state = df.groupby('State')['Product_ID'].nunique()
prod_sold_per_region = df.groupby('Region')['Product_ID'].nunique()

prod_sold_per_state

State
Alabama                   61
Arizona                  206
Arkansas                  57
California              1204
Colorado                 171
Connecticut               81
Delaware                  95
District of Columbia      10
Florida                  345
Georgia                  175
Idaho                     21
Illinois                 435
Indiana                  142
Iowa                      30
Kansas                    24
Kentucky                 131
Louisiana                 42
Maine                      8
Maryland                 103
Massachusetts            134
Michigan                 236
Minnesota                 86
Mississippi               52
Missouri                  66
Montana                   15
Nebraska                  38
Nevada                    38
New Hampshire             27
New Jersey               129
New Mexico                36
New York                 828
North Carolina           229
North Dakota               7
Ohio                     411
Oklahoma                  65
Oregon                   120
Pennsylvania             496
Rhode Island              56
South Carolina            40
South Dakota              12
Tennessee                173
Texas                    773
Utah                      53
Vermont                   11
Virginia                 211
Washington               447
West Virginia              4
Wisconsin                106
Wyoming                    1
Name: Product_ID, dtype: int64